### ISSUE TITLE
Include explanation in "oops something's wrong" alerts

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#473] opened 2017-02-17 15:53 UTC
If there is an error and the "oops, something's wrong" message is displayed to the user, include text about the issue, such as "comment required" or "tag required"

**Comment by Guihrmsfo** [comment] 2017-02-17 15:56
It's not an issue, it's an error message when the cause is unknown.
There are customized messages for such cases (i.g. comment required).
You can close this issue since #472 covers the situation.
I can change the text for something more appropriate if desirable.

**Comment by nathanverrill** [comment] 2017-02-17 16:01
How is there something where the cause is unknown?

**Comment by nathanverrill** [comment] 2017-02-17 16:02
Unless it's a really really far out edge case that fails the checks. Seems this is a simple form that should be easy to validate. I would put text in that says "Use the message box below to let us know what you were attempting to do and we will resolve it."

**Comment by Guihrmsfo** [comment] 2017-02-17 16:04
In the code, when we try to save the review there are some cases we know why the review wouldn't be saved, like when the comment has not enough characters.
If it doesn't match any of the known issues, this message is displayed.

**Comment by nathanverrill** [comment] 2017-02-17 16:16
I would put #character check in the frontend so it is a faster check for the user

**Closed as completed** 2017-03-10 19:53 UTC
Labels: QA
