### ISSUE TITLE
Critical: Evocoin Gifting Doesn't Occur Until after another review is given, and then message is alerted multiple times.

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#442] opened 2017-02-08 17:42 UTC
I logged in as Administrador on dev
I had 5 evocoins
I went to edwin52's profile page and attempted to gift. the system did not respond and our evocoin counts did not adjust
I went to Río Misisip's page and submitted a review. When I did, I got the success message for awarding the Evocoins to edwin52 (attached)
After clicking close, I got the message again
After clicking close, I got the message a third time
Then none of the links were active on the page (nav, profile link in top-right, etc)
I never received feedback for submitting the review, nor did my evocoin increment
It might be unrelated, but chrome inspector shows a "property cannot be read onInputChanged of undefined error"

![image](https://cloud.githubusercontent.com/assets/273429/22748680/701ad376-edf0-11e6-8caf-be6a7e868d66.png)

![image](https://cloud.githubusercontent.com/assets/273429/22748768/c7f19864-edf0-11e6-8a37-6b59a55faad4.png)

**Comment by JayantGandhi** [comment] 2017-02-08 18:04
@Guihrmsfo, any ideas since you worked on this feature?
We should also make sure that the ajax response updates the evocoin readouts on the page too.

@nathanverrill, those console errors look like it might be one of your chrome plugins (not evoke)

**Comment by Guihrmsfo** [comment] 2017-02-08 18:15
Yes, I guess I forgot to update the new popup system for this feature. The multiple alerts are caused by the alert queueing. We'll fix it soon.

**Comment by nathanverrill** [comment] 2017-02-08 18:39
Thanks @JayantGandhi !

**Comment by nathanverrill** [comment] 2017-02-08 19:02
@Guihrmsfo kindly add this to the Wiki - that when a feature is added to look at the pop-up system

**Comment by Guihrmsfo** [comment] 2017-02-08 19:07
@nathanverrill 
Are you sure? I don't think that's needed since the reverse happened:
The pop-up system had been updated and this feature's alert (developed before the newer system) stopped working until now (that we realized it wasn't working). 
If we'd develop a new feature the pop-up system wouldn't stop working.

**Comment by Guihrmsfo** [comment] 2017-02-08 19:08
@nathanverrill 
I updated the dev server, can you try it again?

**Comment by nathanverrill** [comment] 2017-02-08 20:15
@Guihrmsfo I was only saying we need to keep track of coding things to look out for features when they're added so we know where there are special things to check. Know what I mean?

Just gave it a go - sometimes it works, and sometimes it doesn't. I've been able to make it work, but then tried again (did a review to earn coin after trying to gift, got gift message instead of review success after submitting review)

**Comment by Guihrmsfo** [comment] 2017-03-08 20:00
A new fix has been deployed #562

**Closed as completed** 2017-03-10 20:31 UTC
Labels: QA, critical
