### ISSUE TITLE
Activity Link Broken on Evidence Review Box

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#213] opened 2016-10-13 20:36 UTC
Goes to page not found on both dev and prod.

<img width="834" alt="broken-link" src="https://cloud.githubusercontent.com/assets/273429/19365966/d6ad3d88-915a-11e6-959c-59b389610dbc.png">

**Comment by nathanverrill** [comment] 2016-10-18 14:59
What's the status on this one?

Anything related to reviewing evidence is a high priority.

**Comment by nathanverrill** [comment] 2016-10-26 16:42
This occurs on the dashboard stream when logged in as a mentor. Does not occur on player profile stream.

**Comment by JayantGandhi** [comment] 2016-11-04 13:48
@nathanverrill - the issue is mentors don't have access to activities pages...and if the user is not on that specific author's team they also won't be able to view it. It's how humhub has things structured within content within spaces....There's no easy fix for this besides rewriting how activities work...

**Comment by nathanverrill** [comment] 2016-11-04 14:14
how about toggle a show/hide for the activity text?

**Closed as completed** 2016-11-09 15:14 UTC
Labels: QA, high priority
