### ISSUE TITLE
PHP Error when updating prize name, unless re-upload image

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#73] opened 2016-08-03 17:02 UTC
Go into admin, change prize name, save... Error. If I re-upload the same image there is no error. (I was changing the name to Spanish)

PHP Fatal Error – yii\base\ErrorException

Call to a member function saveAs() on a non-object
1. in /srv/www/dev.humhub.m00.com.br/protected/modules/prize/controllers/AdminController.php at line 49
40414243444546474849505152535455565758    }

```
public function actionUpdate($id)
{
    $model = Prize::findOne(['id' => Yii::$app->request->get('id')]);

    if ($model->load(Yii::$app->request->post())) {
      $model->created_at = date("Y-m-d H:i:s");
      $model->image = UploadedFile::getInstance($model, 'image');
      $model->image->saveAs('uploads/' . $model->image->baseName . '.' . $model->image->extension);
      $model->image = 'uploads/' . $model->image->baseName . '.' . $model->image->extension;

      if ($model->save()) {
        return $this->redirect(['index']);
      }
    }

    return $this->render('prize/update', array('model' => $model));
}
```
1. yii\base\ErrorHandler::handleFatalError()

**Comment by JayantGandhi** [comment] 2016-08-03 18:11
duplicate of #56

**Closed as completed by JayantGandhi** 2016-08-03 18:11 UTC
